image: nberlette/gitpod-enhanced

tasks:
  - name: "pnpm"
    init: pnpm install
    command: pnpm dev
    openMode: split-left

ports:
  - name: "Development"
    port: 3000
    onOpen: open-preview
  - name: "Production"
    port: 5000
    onOpen: open-browser

github:
  prebuilds:
    branches: true
    addBadge: true
    addLabel: true
    addCheck: true

gitConfig:
  bash.showUntracked: "false"
  bash.hideIfPwdIgnored: "false"

vscode:
  extensions:
    - svelte.svelte-vscode
    - esbenp.prettier-vscode
    - voorjaar.windicss-intellisense
    - christian-kohler.npm-intellisense
    - christian-kohler.path-intellisense
    - eamodio.gitlens
