# see https://www.gitpod.io/docs/config-docker
image: nberlette/gitpod-enhanced:latest
ports:
  - name: "Development"
    port: "3000-3100"
    onOpen: notify
  - name: "Production"
    port: 5000
    onOpen: notify
  - port: 24678
    onOpen: ignore
# see https://www.gitpod.io/docs/config-start-tasks
tasks:
  # runs only during prebuild, not on each start!
  - init: pnpm install
  - command: |
      export HMR_HOST=$(gp url 24678)
      pnpm run dev
github:
  prebuilds:
    branches: false
    addBadge: true
    addLabel: true
gitConfig:
  bash.showUntracked: "false"
  bash.hidePwdIfIgnored: "false"
vscode:
  extensions:
    - svelte.svelte-vscode
    - esbenp.prettier-vscode
    - voorjaar.windicss-intellisense
    - christian-kohler.npm-intellisense
    - eamodio.gitlens