# see https://www.gitpod.io/docs/config-docker
image: nberlette/gitpod-enhanced

tasks:
  - command: pnpm i && pnpm run dev
    openMode: split-left

ports:
  - name: "Development"
    port: 3000
    onOpen: open-preview
  - name: "Production"
    port: 5000
    onOpen: open-browser

github:
  prebuilds:
    branches: false
    addBadge: true
    addLabel: true

gitConfig:
  bash.showUntracked: "false"
  bash.hideIfPwdIgnored: "false"

vscode:
  extensions:
    - svelte.svelte-vscode
    - esbenp.prettier-vscode
    - voorjaar.windicss-intellisense
    - christian-kohler.npm-intellisense
    - eamodio.gitlens