image: nberlette/gitpod-enhanced

tasks:
  - name: "pnpm"
    before: pnpm install
    command: pnpm dev

ports:
  - name: "SvelteKit"
    port: 3000
    onOpen: open-preview

github:
  prebuilds:
    master: true
    branches: true
    addBadge: true
    addLabel: true
    addCheck: true
    pullRequests: true
    pullRequestsFromForks: true

gitConfig:
  bash.showUntracked: "false"
  bash.hideIfPwdIgnored: "false"

vscode:
  extensions:
    - svelte.svelte-vscode
    - esbenp.prettier-vscode
    - voorjaar.windicss-intellisense
    - christian-kohler.npm-intellisense
    - christian-kohler.path-intellisense
    - eamodio.gitlens
